# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import library_pb2 as library__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\tinventory\x1a\rlibrary.proto\"@\n\x11\x43reateBookRequest\x12\"\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.inventory.BookH\x00\x88\x01\x01\x42\x07\n\x05_book\"f\n\x0f\x43reateBookReply\x12&\n\x06status\x18\x01 \x01(\x0b\x32\x11.inventory.StatusH\x00\x88\x01\x01\x12\x14\n\x07message\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\n\n\x08_message\",\n\x0eGetBookRequest\x12\x11\n\x04isbn\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_isbn\"n\n\x0cGetBookReply\x12&\n\x06status\x18\x01 \x01(\x0b\x32\x11.inventory.StatusH\x00\x88\x01\x01\x12\"\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0f.inventory.BookH\x01\x88\x01\x01\x42\t\n\x07_statusB\x07\n\x05_book2\x99\x01\n\x10InventoryService\x12\x46\n\nCreateBook\x12\x1c.inventory.CreateBookRequest\x1a\x1a.inventory.CreateBookReply\x12=\n\x07GetBook\x12\x19.inventory.GetBookRequest\x1a\x17.inventory.GetBookReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=53
  _CREATEBOOKREQUEST._serialized_end=117
  _CREATEBOOKREPLY._serialized_start=119
  _CREATEBOOKREPLY._serialized_end=221
  _GETBOOKREQUEST._serialized_start=223
  _GETBOOKREQUEST._serialized_end=267
  _GETBOOKREPLY._serialized_start=269
  _GETBOOKREPLY._serialized_end=379
  _INVENTORYSERVICE._serialized_start=382
  _INVENTORYSERVICE._serialized_end=535
# @@protoc_insertion_point(module_scope)
